### ISSUE TITLE
Logging slows the simulation

### ISSUE THREAD

**Issue by rdriven** [mheidebr/Electric-Car-Racing#26]
It would be nice to have logging not slow down the simulation so much, especially on longer runs. Perhaps some finer control rather than "on" or "off" (commenting out configure_logging()) would useful
Ideas:
* per thread control (e.g. only simulation thread)
* per severity level (e.g. turn off "info" level logging)
* combo of the two above
* Have GUI control level - (e.g. after hitting breakpoint, user can turn on some/all logging then continue simulation with logging "on" from that point forward.

**Comment by mheidebr** [comment]
Closed because argument that can turn off logging allows simulation to run at a reasonable rate
