### ISSUE TITLE
Make an argparser for the simulation

### ISSUE THREAD

**Issue by mheidebr** [mheidebr/Electric-Car-Racing#30]
arg parsing requirements:
- Must be able to turn logging on (default off)
- mus be able to load in car from an external .csv file (required argument for simulation)
- must be able to load in track from an external .csv file (required argument for simulation)
- must be able to specify an output file for the results (optional argument, there must be a default output location)
- must be expandable to more arguments in the future

**Comment by mheidebr** [comment]
possible additional argument for displaying or hiding the gui, not sure on this one yet though

**Comment by rdriven** [comment]
Add to the requirements
- a refactor to have main.py that makes datastore object 
- initializes datastore with track and car profiles from TBD .csv formatted files
- then gives datastore to simulation and visualization
- also processes other input arguments (e.g. logging on|off) either by processing directly or passing along appropriately
- adjust and take into account order of  creation/initialization/start() of simulation (1st) and visualization (2nd) threads appropriately
