### ISSUE TITLE
Format calls in logging strings still take an appreciable amount of time even with logging turned off

### ISSUE THREAD

**Issue by mheidebr** [mheidebr/Electric-Car-Racing#51]
![Screenshot from 2021-02-09 07-04-46](https://user-images.githubusercontent.com/68092883/107375190-b2645500-6aa5-11eb-8314-6c6a5b24543c.png)
With the latest high plains raceway track the formatting calls in logging calls in the physics equation file take ~30 seconds even though logging is turned off. I commented out the logging calls and the simulation runs much faster. We have a logging command line option, but do we have more control to leave the logging statements in and not have that performance hit?
- maybe 2 different versions of functions that used, one with and one without logging. The version used is determined by the logging command
- Get rid of logging?

**Comment by rdriven** [comment]
I think perhaps we can get rid of logging if we're all doing VS Code debugging, runsnake, etc. It may have made sense during our early development, but we've moved on to a better debug method. 

If we move development to jupyter lab it may make sense to leave logging statements in and short circuit them for now. I just don't have enough experience debugging in jupyter yet....

I guess architecturally, if we get rid of the MainWindow GUI by going with jupyter we could probably get rid of the who datastore.py/deepcopy to speed things up too.

**Comment by mheidebr** [comment]
addressed by not calling `configure_logging()` function if logging isn't turned on
