### ISSUE TITLE
Incorporate imported csv data into DataStore

### ISSUE THREAD

**Issue by john-marinelli** [mheidebr/Electric-Car-Racing#56]
After figuring out loading csv data, we need to put it to use. This includes finding values in our code that correspond to fastsim variables that have been loaded.

**Comment by john-marinelli** [comment]
Rather, we incorporate the data into electric_car_properties/track_properties, and then into DataStore.

**Comment by mheidebr** [comment]
closing, imported data is passed around in a dict which is good enough for now
